version: '3.8'

services:
  api:
    build: .
    container_name: agiliza.ai
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/agiliza.ai_db
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: agiliza.ai_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agiliza.ai_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
